### ISSUE TITLE
Overlay areas on map always black 

### ISSUE THREAD

**Issue by aidanboran** [CitiLogics/citilogics-geoloop-panel#8]
Hi
I have installed geoloop plugin using the standard NOAA data set mentioned.

Query part is working fine but I am only seeing black (i.e. single colours) on the map...animation thro the frames works fine - just always black

Using Grafana 4.6.2 on a raspberry pi.
geoloop v1.1.1

![screen shot 2018-05-29 at 15 58 20](https://user-images.githubusercontent.com/3597989/40667260-9af41e60-6359-11e8-865f-df55e768b054.png)
![screen shot 2018-05-29 at 16 02 26](https://user-images.githubusercontent.com/3597989/40667417-062240f4-635a-11e8-9c87-6ba3c4dbdfa7.png)

**Comment by samhatchett** [comment]
I'm not exactly clear on the `Metrics` tab screenshot - if the query doesn't generate data that can be related to the geojson via a matched (influx tag) => (json path), then the polygons would probably be rendered solid black. Could you, in addition to the above, also paste in a sample influx result set, and the relevant geojson to make sure that all the pieces are coordinated?

**Comment by aidanboran** [comment]
thanks. Here are the two data sets...

<img width="1528" alt="screen shot 2018-05-30 at 18 33 41" src="https://user-images.githubusercontent.com/3597989/40737293-365f334c-6438-11e8-93c4-7dae4d43a88a.png">
<img width="1605" alt="screen shot 2018-05-30 at 18 34 46" src="https://user-images.githubusercontent.com/3597989/40737349-57e21fd4-6438-11e8-831f-8f74b33c50f5.png">

**Comment by samhatchett** [comment]
ok, so it looks like the query is not coding the location data in the results set. if you add a `GROUP BY tag(location)` to the Metrics panel, this data will get carried through to the results, and it should all work.

**Comment by aidanboran** [comment]
excellent. that was it. thank you.
